### ISSUE TITLE
install is error，the down  is infos

### ISSUE THREAD

**Issue by liujieyuu** [YellowApple/tldrb#2]
pastjiedeMBP:ios pastjie$ gem install tldrb
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
 pastjiedeMBP:ios pastjie$ sudo gem install tldrb
Password:
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/restclient

**Comment by grosser** [comment]
`sudo gem install tldrb`

**Comment by YellowApple** [comment]
Which operating system are you running (I'm assuming OS X given the paths, but which version)?  Are you using any Ruby version managers (RVM, chruby, etc.)?

**Comment by liujieyuu** [comment]
@YellowApple  operating system:OSX 10.11.2 (15C50),i installde homebrew，and then,run :brew tap tldr-pages/tldr && brew install tldr

**Comment by YellowApple** [comment]
The client on Homebrew is the [C++-based client](https://github.com/tldr-pages/tldr-cpp-client), last I checked.

As for the issue with `tldrb`, it looks like it's related to [this StackOverflow entry regarding gem installation on El Capitan](http://stackoverflow.com/questions/31972968/cant-install-gems-on-os-x-el-capitan).  I'd suggest following the suggestions in the marked answer to install `tldrb` to somewhere other than `/usr/bin` (like `/usr/local/bin` if you want it system-wide, or to `~/bin` if you just want it for your own user).  I don't have a machine running El Capitan (or OS X at all, for that matter) to test with, however.

Closing this issue due to it being non-tldrb-specific.
